package no.nav.k9.abakus.registerdata.tjeneste;

public enum RegisterdataElement {
    ARBEIDSFORHOLD,
    YTELSE,
    INNTEKT_PENSJONSGIVENDE,
    INNTEKT_BEREGNINGSGRUNNLAG,
    INNTEKT_SAMMENLIGNINGSGRUNNLAG,
    INNTEKT_UNGDOMSYTELSEGRUNNLAG,
    LIGNET_NÆRING
}
