name: Bygg pull request

on:
  pull_request_target:
    paths-ignore:
      - '**.md'
      - '**.MD'
      - '.gitignore'
      - 'LICENCE'
      - 'CODEOWNERS'

jobs:
  build:

    runs-on: ubuntu-latest

    services:
        postgres:
          image: postgres:15
          env:
            POSTGRES_USER: k9_abakus_unit
            POSTGRES_PASSWORD: k9_abakus_unit
            POSTGRES_DB: k9_abakus_unit
          ports:
            - 5432:5432
          # needed because the postgres container does not provide a healthcheck
          options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build
        shell: bash
        run: |
          mvn verify --quiet --batch-mode --settings .github/.m2/settings.xml --file pom.xml -DtrimStackTrace=false
        env:
          TZ: "Europe/Oslo"
          GITHUB_TOKEN: ${{ secrets.READER_TOKEN }}
          GH_ACCESS_TOKEN: ${{ secrets.READER_TOKEN }}
          DATASOURCE_HOST: localhost
          DATASOURCE_PORT: ${{ job.services.postgres.ports[5432] }} # get randomly assigned published port
