name: Monitor dependencies with Dependabot
on:
  push:
    branches:
      - master
    paths:
      - "pom.xml"
      - "**/pom.xml"
  workflow_dispatch:
  
jobs:
  deps:
    permissions:
      contents: write
      security-events: write
    name: k9-felles mvn dependency scan
    uses: navikt/sif-gha-workflows/.github/workflows/maven-dependency-submission.yml@main
    secrets: inherit
