name: "Pull Request Labeler"
on:
  pull_request_target:

jobs:
  triage:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/labeler@f1a63e87db0c6baf19c5713083f8d00d789ca184 # ratchet:actions/labeler@v6.0.0
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        sync-labels: true
